# Generated by Django 3.2.12 on 2022-03-17 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brewery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('obdb_id', models.CharField(max_length=200)),
                ('brewery_type', models.CharField(max_length=200)),
                ('street', models.CharField(max_length=200)),
                ('address_2', models.CharField(max_length=200)),
                ('address_3', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=200)),
                ('state', models.CharField(max_length=200)),
                ('county_province', models.CharField(max_length=200)),
                ('postal_code', models.CharField(max_length=200)),
                ('website_url', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=200)),
                ('country', models.CharField(max_length=200)),
                ('longitude', models.CharField(max_length=200)),
                ('latitude', models.CharField(max_length=200)),
                ('tags', models.CharField(max_length=200)),
                ('created', models.DateTimeField()),
            ],
        ),
    ]
