# Generated by Django 3.2.12 on 2022-03-17 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brewery',
            name='created',
        ),
        migrations.AlterField(
            model_name='brewery',
            name='address_2',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='brewery',
            name='address_3',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='brewery',
            name='city',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='brewery',
            name='country',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='brewery',
            name='county_province',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='brewery',
            name='latitude',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='brewery',
            name='longitude',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='brewery',
            name='phone',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='brewery',
            name='postal_code',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='brewery',
            name='state',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='brewery',
            name='street',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='brewery',
            name='tags',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='brewery',
            name='website_url',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
