# Generated by Django 3.2.12 on 2022-03-17 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0003_auto_20220316_2307'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brewery',
            name='id',
        ),
        migrations.AlterField(
            model_name='brewery',
            name='obdb_id',
            field=models.CharField(max_length=200, primary_key=True, serialize=False),
        ),
    ]
